spring:
  application:
            name: budgetapi

  datasource:
    url: jdbc:mysql://localhost:3306/budgetdata?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

app:
  jwtSecret: ${HASH_KEY}

server:
  port: 8080

